### PR TITLE
Android chore update for fhir north

### PR DESCRIPTION
**Pull request by markiantorno**
Let me know if this is appropriate for this project, or if this should be in it's own thing. I wanted to update the tools for the FHIR north thing this Wednesday.

Any feedback is welcome.

### CODE REVIEW

**Comment by jamesagnew** [comment]
@botunge would you be able to give this a review? Mark works with me at University Health Network and has beefed this up to use as a demo for an upcoming connectathon. Would love to get your thoughts on the updates.

**Comment by jamesagnew** [comment]
Hmm, travis CI seems to have failed.. i wonder what's going on there

**Comment by botunge** [comment]
I'll take a look at the code in a couple og hours

Den søn. 23. apr. 2017 20.33 skrev James Agnew <notifications@github.com>:

**Comment by jamesagnew** [comment]
Thanks!

@markiantorno I think you need to update the android lib version in `.travis.yml` in order for the CI server to build correctly.

**Comment by markiantorno** [comment]
Yeah I pooched that

sorry

**Comment by markiantorno** [comment]
As a side note, @botunge I'm planning on adding a Observation UI similar to the patient one, probably tomorrow.

**Comment by botunge** [comment]
the purpose of the project was to ensure that hapi-fhir would work in Android. This commit takes the project in another direction. I like the idea of a android client showcasing different usages of the FHIR api. Just not sure it should be merged with this, since this is only here to ensure no changes are committed to HAPI which brakes Android.
@jamesagnew Why not make a hapifhir/androidshowcase project or something like that, where this change could be put. AFAIK the code is fine. (you might want to remove some create by mark comments and add som Apache 2 Copyright notice.)

**Comment by markiantorno** [comment]
Yeah, James had suggested something along those lines and I agree it probably would be best to put it in its own repo. @jamesagnew would you rather I do this under my own GitHub account or nested under fhir? For the short term, I'm just going to put it under my GitHub account so that it's ready for the conference on Wednesday.

**Comment by markiantorno** [comment]
Thanks for taking the time to look at it @botunge.

**Comment by jamesagnew** [comment]
@markiantorno if you're interested in posting this as a project right in this organization I certainly wouldn't object :)

**Pull request closed without merging**
